# Generated by Django 5.2.7 on 2025-10-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_productimage_image'),
        ('user', '0002_address_cartitem_productfavorite_userproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfavorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.productsku', verbose_name='商品'),
        ),
    ]
