# Generated by Django 5.2.7 on 2025-10-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_productfavorite_user_postfavorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfavorite',
            options={'verbose_name': '帖子收藏', 'verbose_name_plural': '帖子收藏'},
        ),
    ]
