# Generated by Django 5.2.7 on 2025-11-03 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_productreview'),
        ('user', '0005_alter_postfavorite_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfavorite',
            options={'ordering': ['-created_at'], 'verbose_name': '商品收藏', 'verbose_name_plural': '商品收藏'},
        ),
        migrations.AddField(
            model_name='productfavorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='收藏时间'),
        ),
        migrations.AlterField(
            model_name='productfavorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.productspu', verbose_name='商品SPU'),
        ),
    ]
