# Generated by Django 5.2.7 on 2025-10-20 09:17

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='属性名称')),
            ],
            options={
                'verbose_name': '商品属性',
                'verbose_name_plural': '商品属性',
            },
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('sku_code', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, verbose_name='SKU编码')),
                ('title', models.CharField(max_length=200, verbose_name='SKU标题')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品SKU',
                'verbose_name_plural': '商品SKU',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='属性值')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shopping.attribute', verbose_name='所属属性')),
            ],
            options={
                'verbose_name': '属性值',
                'verbose_name_plural': '属性值',
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.category', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='shopping.productsku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
            },
        ),
        migrations.CreateModel(
            name='ProductSKUAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.attribute', verbose_name='属性')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.attributevalue', verbose_name='属性值')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='shopping.productsku', verbose_name='所属SKU')),
            ],
            options={
                'verbose_name': 'SKU属性值',
                'verbose_name_plural': 'SKU属性值',
            },
        ),
        migrations.CreateModel(
            name='ProductSPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '商品SPU',
                'verbose_name_plural': '商品SPU',
            },
        ),
        migrations.AddField(
            model_name='productsku',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='shopping.productspu', verbose_name='所属SPU'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='图片')),
                ('is_main', models.BooleanField(default=False, verbose_name='是否主图')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopping.productsku', verbose_name='SKU')),
                ('spu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopping.productspu', verbose_name='SPU')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.CreateModel(
            name='ProductSPUAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.attribute', verbose_name='属性')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='shopping.productspu', verbose_name='所属SPU')),
            ],
            options={
                'verbose_name': 'SPU属性配置',
                'verbose_name_plural': 'SPU属性配置',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='shopping_ca_parent__ec774d_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tree_id', 'lft'], name='shopping_category_tree_id_8cfe'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['quantity'], name='shopping_in_quantit_ba9511_idx'),
        ),
        migrations.AddIndex(
            model_name='productskuattributevalue',
            index=models.Index(fields=['sku'], name='shopping_pr_sku_id_e48e85_idx'),
        ),
        migrations.AddIndex(
            model_name='productskuattributevalue',
            index=models.Index(fields=['attribute'], name='shopping_pr_attribu_a23cac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productskuattributevalue',
            unique_together={('sku', 'attribute')},
        ),
        migrations.AddIndex(
            model_name='productspu',
            index=models.Index(fields=['category', 'is_active'], name='shopping_pr_categor_545fef_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['spu', 'is_active'], name='shopping_pr_spu_id_954adb_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['price'], name='shopping_pr_price_bc8961_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['spu', 'is_main'], name='shopping_pr_spu_id_d64987_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['sku', 'is_main'], name='shopping_pr_sku_id_68c1b8_idx'),
        ),
        migrations.AddIndex(
            model_name='productspuattribute',
            index=models.Index(fields=['spu'], name='shopping_pr_spu_id_d70c10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productspuattribute',
            unique_together={('spu', 'attribute')},
        ),
    ]
