# Generated by Django 5.2.7 on 2025-10-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': '属性', 'verbose_name_plural': '属性'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='productsku',
            options={'verbose_name': 'SKU', 'verbose_name_plural': 'SKU'},
        ),
        migrations.AlterModelOptions(
            name='productspu',
            options={'verbose_name': 'SPU', 'verbose_name_plural': 'SPU'},
        ),
        migrations.AlterModelOptions(
            name='productspuattribute',
            options={'verbose_name': 'SPU属性', 'verbose_name_plural': 'SPU属性'},
        ),
        migrations.AddField(
            model_name='productspu',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='productspu',
            name='series',
            field=models.CharField(blank=True, max_length=100, verbose_name='系列'),
        ),
        migrations.AddIndex(
            model_name='productspu',
            index=models.Index(fields=['brand'], name='shopping_pr_brand_618320_idx'),
        ),
        migrations.AddIndex(
            model_name='productspu',
            index=models.Index(fields=['series'], name='shopping_pr_series_738083_idx'),
        ),
    ]
