# Generated by Django 5.2.7 on 2025-10-20 11:58

import shopping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_attribute_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=shopping.models.product_image_upload_path, verbose_name='图片'),
        ),
    ]
