# Generated by Django 5.2.7 on 2025-10-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('shopping', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(blank=True, to='shopping.productsku', verbose_name='关联产品'),
        ),
    ]
