# Generated by Django 5.2.7 on 2025-10-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_image_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='posts/images/%Y/%m/%d/', verbose_name='图片文件'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='posts', to='forum.image', verbose_name='插入图片'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['file'], name='forum_image_file_8adb76_idx'),
        ),
    ]
