# Generated by Django 5.2.7 on 2025-10-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_image_post_alter_image_file_alter_post_images_and_more'),
        ('shopping', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': '帖子', 'verbose_name_plural': '帖子'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at'], 'verbose_name': '回复', 'verbose_name_plural': '回复'},
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(blank=True, to='shopping.productspu', verbose_name='关联产品'),
        ),
    ]
