# Generated by Django 5.2.7 on 2025-10-31 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_post_options_alter_reply_options_post_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
