# Generated by Django 5.2.7 on 2025-10-23 15:36

import django.db.models.deletion
import publish.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='艺术家姓名')),
                ('image', models.ImageField(blank=True, upload_to='publish/artists/', verbose_name='艺术家图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '艺术家',
                'verbose_name_plural': '艺术家',
                'indexes': [models.Index(fields=['name'], name='publish_art_name_671adc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='专辑名')),
                ('cover_image', models.ImageField(blank=True, upload_to=publish.models.album_upload_path, verbose_name='封面图片')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='发行日期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否发布')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.artist', verbose_name='艺术家')),
            ],
            options={
                'verbose_name': '专辑',
                'verbose_name_plural': '专辑',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='音乐标题')),
                ('duration', models.DurationField(verbose_name='时长')),
                ('file', models.FileField(upload_to=publish.models.music_upload_path, verbose_name='音乐文件')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否发布')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='publish.album', verbose_name='所属专辑')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.artist', verbose_name='艺术家')),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='视频标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('file', models.FileField(upload_to='videos/', verbose_name='视频文件')),
                ('thumbnail', models.ImageField(blank=True, upload_to='videos/thumbnails/', verbose_name='缩略图')),
                ('duration', models.DurationField(verbose_name='时长')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'indexes': [models.Index(fields=['is_active'], name='publish_vid_is_acti_1a44d0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist'], name='publish_alb_artist__49119d_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['is_active'], name='publish_alb_is_acti_9c3d90_idx'),
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['artist'], name='publish_mus_artist__52a429_idx'),
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['album'], name='publish_mus_album_i_1edec0_idx'),
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['is_active'], name='publish_mus_is_acti_b238d0_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['is_active'], name='publish_not_is_acti_6036e9_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['created_at'], name='publish_not_created_15393d_idx'),
        ),
    ]
