# Generated by Django 5.2.7 on 2025-10-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='track_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='轨道号'),
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['track_number'], name='publish_mus_track_n_7b2ddb_idx'),
        ),
    ]
