# Generated by Django 5.2.7 on 2025-10-24 02:28

import publish.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_music_track_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(blank=True, upload_to=publish.models.music_upload_path, verbose_name='音乐文件'),
        ),
    ]
