# Generated by Django 5.2.7 on 2025-10-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_alter_music_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.DurationField(blank=True, verbose_name='时长'),
        ),
    ]
