# Generated by Django 5.2.7 on 2025-10-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_alter_music_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='时长'),
        ),
    ]
