# Generated by Django 5.2.7 on 2025-10-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_alter_music_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bilibili_url',
            field=models.URLField(blank=True, null=True, verbose_name='B站外链'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(max_length=20, null=True, verbose_name='视频类型'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='时长'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='视频文件'),
        ),
    ]
