# Generated by Django 5.2.7 on 2025-10-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_video_bilibili_url_video_video_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('live', 'Live'), ('interview', 'Interview'), ('documentary', 'Documentary')], default='live', max_length=20, verbose_name='视频类型'),
        ),
    ]
